name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "uv.lock"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@master

  basedpyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"
          version: "latest"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run Basedpyright
        run: uvx basedpyright

  test-screenshot:
    name: Test Screenshot
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-screenshot-coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    env:
      UV_NO_SYNC: 1
      PYTHON_VERSION: ${{ matrix.python-version }}
      FORTNITE_API_KEY: ${{ secrets.FORTNITE_API_KEY }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Install Playwright
        run: uv run playwright install chromium-headless-shell --with-deps

      - name: Run Pytest
        run: uv run poe test-screenshot

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          env_vars: PYTHON_VERSION
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: PYTHON_VERSION
          use_oidc: true

  test-matcher:
    name: Test Matcher
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-matcher-coverage-${{ github.ref }}
      cancel-in-progress: true

    env:
      UV_NO_SYNC: 1
      FORTNITE_API_KEY: ${{ secrets.FORTNITE_API_KEY }}
      PYTHON_VERSION: "3.12"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}
          version: "latest"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Install Playwright
        run: uv run playwright install chromium-headless-shell --with-deps

      - name: Run Pytest
        run: uv run poe test-matcher

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          env_vars: PYTHON_VERSION
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: PYTHON_VERSION
          use_oidc: true
